### ISSUE TITLE
copy sample-runner from kendoui-bridge

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#10]
copy to implement the sample pages

**Comment by adriatic** [comment]
The current content in https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge supports the identical method for creating sample pages - I used the code that was the "inspiration" for the subsequent code runner, because the code - runner was implemented at the stage when the bridge was already using several aureliaized KendoUI controls and there were too many hacks involved to remove these while preserve the code runner in that "older version" of the bridge.

##### The reason I dug back in the past is solely to remove the pressure on @JeroenVinke (to accelerate the plugin builder and it's future sub-components) while allow @Thanood to start working on Materialize in a lot more comfortable environment that plunker offers.

My expectation from the above described beginning for @Thanood was that at the point the plugin builder is ready (it's currently waiting for new jspm and because of that outside of our control), @Thanood could use the https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/1 article to recreate the project from scratch to the point where plugin builder gets used and then simply copy all wrappers and all sample consumer apps from the bridge project used up to that point.

@Thanood @JeroenVinke - you are completely free to take any approach, different from what I prepared, if that seems not the best for your taste. :-)

**Comment by Thanood** [comment]
Would need a lot more effort than just copying. Therefore closed. :smile:

**Comment by adriatic** [comment]
:smile_cat:
