### ISSUE TITLE
error running gulp watch 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-materialize-bridge#14]
Not sure whether this is in any way related to just added [fix for handling `dist` folder problems](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/07e3e9fc2680c8efe1be14b514352a177c31f014) however, I am getting this:

```
λ gulp -watch
C:\work\aurelia-ui-toolkits\aurelia-materialize-plugin\node_modules\gulp-sass\node_modules\node-sass\lib\extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in C:\work\aurelia-ui-toolkits\aurelia-materialize-plugin\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-47\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (C:\work\aurelia-ui-toolkits\aurelia-materialize-plugin\node_modules\gulp-sass\node_modules\node-sass\lib\extensions.js:158:11)
    at Object.<anonymous> (C:\work\aurelia-ui-toolkits\aurelia-materialize-plugin\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:16:36)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\work\aurelia-ui-toolkits\aurelia-materialize-plugin\node_modules\gulp-sass\index.js:176:21)
    at Module._compile (module.js:425:26)
```

Note earlier today, I was able to run `gulp watch` in this project without a peep

**Comment by charlespockert** [comment]
Thinking this is maybe related to your jspm install? Did you try updating jspm earlier, we briefly chatted about it - wondering if this might have partially broken your install as it broke mine until I ran the install command again... not sure why (problems with the node build steps for the deps)

**Comment by adriatic** [comment]
I figured (after a long search at the wrong place). In addition to your fix for `dist`folder issues, few hours before @Thanood pushed **[his changes](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/979b3597e502509625177bc94df1969e30921f50)** - and I failed to realize that. so, the `Error: The `libsass` binding was not found in C` was the consequence of changes that @Thanood made - and the fix for that is to to run
```
npm rebuild node-sass
```
So, I raised a good alarm at a wrong place (with @charlespockert) who had nothing with that issue. My apologies, Sir Charles :-)

**Comment by Thanood** [comment]
I'm curious how I did that considering there is not one gulp task needing gulp-sass. :smile: 
I must say that there isn't even a ```gulp-sass``` module installed in my tree which could throw that error. So you have to be using a somewhat different setup, right? How did that happen?

I'd like to investigate further on that because of my lacking experience with gulp (and sass) and my intention to gather some more experience. The only hint so far is right in the error message:
```This usually happens because your node version has changed.``` - did it change then?

Here's a longer explanation:
> For context this error is almost always because npm install ran with a
different version of node than the version you're current running.

>Since node-sass is a native module we build the c++ code on installation.
That code is tied to the version of node that ran the installation. If you
change your node version the extension needs to be rebuilt, that's what
npm rebuild does.

I must also say that I **did** pull gulp-sass-json to try that out but also deleted it. So I cannot rule out that there may be some "rest" depending on gulp-sass. But then (looking at my changes at package.json again) this would have occured on my tree, right?

So how can we solve this? Could you run a quick diff on a fresh clone from this repo? there must be a difference.

On the other hand:
> the Error: Thelibsassbinding was not found in C was the consequence of changes that @Thanood made

Maybe you already know what change caused this. If so, could you tell me what it is?

**Comment by charlespockert** [comment]
For what it's worth, I ran it on mine and it all ran fine...

**Comment by adriatic** [comment]
I have no problems once I run `npm rebuild node-sass` - and I now understand why did I have to do it.

**Comment by Thanood** [comment]
So... Can we close it? :smile: 
Was it the node version?

**Comment by adriatic** [comment]
The first time I run Materialize catalog app, it was "pure" Bootstrap (no use of any Materialize bits), so it run fine and displayed the `click-counter` application. 

The next time (without me understanding it) it was already a Materialize bits dependent and it did not run (of course). After running all needed npm / jspm installs one of them must have failed and I got that `The `libsass` binding was not found in C:\work\aurelia-ui-toolkits\aurelia-m` error.

Executing `npm rebuild node-sass` fixed everything.

I am running node 5.1.1
