### ISSUE TITLE
Modal Overlay stays when navigating with a md-modal-triggers button

### ISSUE THREAD

**Issue by Kukks** [aurelia-ui-toolkits/aurelia-materialize-bridge#167]
When having a modal open, and you click a button within the modal that has a modal trigger attribute and also redirects you to a new route, the modal closes and the page gets redirected, however the modal overlay stays there until the page is clicked where it then fades out. Below is the elements that stays.
```
<div class="lean-overlay" id="materialize-lean-overlay-2" style="z-index: 1002; display: block; opacity: 0.5;"></div>
```

**Comment by Thanood** [comment]
Please excuse me if this is a stupid question but why would you have a modal-trigger inside a modal? I just fail to see a use-case. :smile: 

What the modal-trigger attribute basically does is create a new modal. So if you click on that it invokes [openModal](https://github.com/Dogfalo/materialize/blob/master/js/leanModal.js#L185), creating an overlay.

There are only [three cases](https://github.com/Dogfalo/materialize/blob/master/js/leanModal.js#L46-L60) which actually close the modal and thus remove the overlay:
* clicking outside the modal with ```dismissible``` set
* pressing ESC while the modal ist displayed
* clicking on a button with class ```modal-close``` set

Maybe it's best if the button which redirects the page also closes the modal (by having a ```modal-close``` class).

Having said that, there is a ```closeModal``` function in Materialize we could provide in the attribute to be able to have the router close the overlay, f.i. with an event subscribed to the router.

But I think I will have to try this. As I'm typing this post it's all a little abstract. :smile:

**Comment by Thanood** [comment]
I've created a gist to reproduce but I don't get this behaviour. Can you please have a look at this:
https://gist.run/?id=46ed13418d516f3af2c8739998acfd91

Maybe adjust it so that it reproduces the bahaviour you mentioned above.
I've also tried to put a modal-trigger attribute on the "agree" button in this modal. I've deleted this experiment to have a "clean" setup for you.

**Comment by Thanood** [comment]
To be more specific: I can actually reproduce this when I leave out the ```modal-close``` class on the "agree" button in the modal. But adding it again resolves this.

**Comment by Kukks** [comment]
Hey, sorry, I meant to write `modal-close` :) Let me look into the gist and will let you know

**Comment by Kukks** [comment]
Weird, I have the exact flow within my application. The modal actually goes away however the background stays. I made sure modal-action and modal-close classes are present on the button too.

**Comment by Thanood** [comment]
Strange.. Maybe you have done something in another way that is not too obvious. :smile:

**Comment by Thanood** [comment]
Is still happening? Couldn't reproduce it in the last two weeks..

**Comment by Kukks** [comment]
Still happening on my local. I just have some issues which aren't allowing
me to upload onto the staging server to show you. Will keep you updated.

**Comment by Kukks** [comment]
We figured it out. It is about navigating away from the page before the close modal can execute. A hack was to simulate a click on the overlay after router navigation. Not nice but works for now. Below is the solution:


https://gist.github.com/Kukks/9ea882e33471784ce2a12c5ddc1baa23

**Comment by Thanood** [comment]
Thanks for sharing this. You could also subscribe to a router event, f.i. "router:navigation:complete" ([see here](http://ilikekillnerds.com/2015/09/understanding-aurelia-router-events/) for a good explanation and list of all events).

I'm mentioning it since according to [this SO post](http://stackoverflow.com/questions/28419242/property-change-subscription-with-aurelia/28437456#28437456) `ObserverLocator` should not be used directly.
