### ISSUE TITLE
Disabling the Select Component

### ISSUE THREAD

**Issue by easyt** [aurelia-ui-toolkits/aurelia-materialize-bridge#190]
There doesn't seem to be a way to disable the select component. 

1. Am I missing something?
2. Will you be adding this feature?
3. Is there a way to work around this?

I was hoping to have something similar to the following: md-button="disabled.bind: disableButton"

Thanks.

**Comment by Thanood** [comment]
Good point.. :+1: 

Materialize itself supports disabling its select but changing that "dynamically" is not straightforward possible. By that I mean switching from `disabled` to `enabled` and back.

I've tried to do it and the following works:
* find `.select-wrapper`
* remove the `disabled` class from its `.caret` child
* remove the `disabled` attribute from its `.select-dropdown` child
* remove the `disabled` attribute from the wrapped `select`
* call (basically) this: `$('.select-dropdown').dropdown({'hover': false, 'closeOnClick': false});` (depending on options)

Disabling work in the opposite direction.

I'm sure we can do this in the bridge.
Question is if we should because others may have other workarounds and we shouldn't conflict with those. But I guess if it's a property in the `md-select` attribute it shouldn't conflict..

**Comment by easyt** [comment]
Thanks. I hope it gets built in :)

**Comment by Thanood** [comment]
Demo: https://gist.run/?id=9215cb0cefe0e1701d9c095f828f0676

I'll add it soon.. Monday the latest. :smile:

**Comment by easyt** [comment]
That's great! Thank you.

**Comment by Thanood** [comment]
Implemented just now. :smile:
