### ISSUE TITLE
Missing materialize dependency

### ISSUE THREAD

**Issue by code-chris** [aurelia-ui-toolkits/aurelia-materialize-bridge#195]
Hi,
I've seen that the materialize dependency is missing as npm dependency. It is only listed in the jspm section. Therefore it isn't installed through npm.

Furthermore the library "materialize" seems to be another lib than "materialize-css" .....

**Comment by adriatic** [comment]
Leaving the final answer to @Thanood who is the creator of this bridge, Aurelia-Materialize bridge depends on the SystemJS module loader and because of that, needs to use jspm. See more [here](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/a-production-setup/1)

> Furthermore the library "materialize" seems to be another lib than "materialize-css" .....

Aurelia-materialize-bridge is defined as Material design HTML5 widgets - enhanced by Aurelia, so it can be used like any other Aurelia **[component](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components)**

**Comment by code-chris** [comment]
OK. Thanks, for your explanation.

**Comment by Thanood** [comment]
Hello @code-chris and thanks for aurelia-knockout. :smile: 

As you probably know there are mutliple ways of acquiring Materialize, unfortunately none of them is a real "recommended" way. At the start of this project we had some discussions which would be the best way to define the Materialize dependency.

We have decided to reference the GitHub version because it's the one with the least problems. Also npm-based loaders have not really been in discussion at that time. That has changed now, webpack and requirejs are used and supported in official aurelia projects (webpack-plugin and cli).

I have not been successful getting Materialize to work from npm flawlessly, yet. The npm version has its problems, baked-in dependencies which are not always referenced (HammerJS, Velocity, the `Materialize` global itself), two different versions in the npm distribution (the `bin` and `dist` folders).

Personally, I would even recommend to use the GitHub version of Materialize with npm because in my opinion it is simply better and "just works". But this choice should be a user's choice. Maybe we should declare `materialize-css` a peer dependency.

I think we'd first need to make it work with webpack/requirejs anyway. What do you think?

**Comment by code-chris** [comment]
Thanks for this explanation. Yes, I agree with you that this should be user's choice and that the usage with webpack or requirejs should be improved preferential. I think it makes sense to add `materialize-css` as peer-dependency to add a relationship in package.json

Is the installation through GitHub the reason why `materialize` is required here (https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/index.js#L1) instead of `materialize-css`?

**Comment by Thanood** [comment]
That is just a convenience addition. Users could as well import that in `main.js` before activating the bridge. With SystemJS it would be easy to create an alias for materialize-css which would be called "materialize" to make this work. Or at least that has been my thought at that time. :smile: 

I'm not sure if it's (easily) possible with requirejs, pretty sure that it's possible with webpack.
Actually, I know it's possible with requirejs but I don't know how that would work with the current version of the CLI.

I couldn't find any good solution for requirejs - or at least any solution that is not a fork of requirejs. For webpack there is at least this loader: https://github.com/Zevran/materialize-loader

But I agree that the import in `index.js` is not really a good way to load Materialize when the source of that library should be a user's choice.

**Comment by Thanood** [comment]
We're not far from a solution, I think.

![image](https://cloud.githubusercontent.com/assets/677826/16408440/16d41de6-3d19-11e6-8956-dfe0ea4e5a5f.png)

This is the current webpack skeleton. It's not running the bridge but Materialize standalone. The critical parts have always been getting all Materialize globals to work and to be able to `<require from="...">`. The image of the demo above uses both without any problems.

**Comment by Thanood** [comment]
Note to myself - webpacks *most probably* runs materialize-bridge when this is done. It runs in parts - tried with some components of the bridge (badge, nav-bar).

* remove `import 'materialize';` from `index.js` and describe including an own distribution
* match global resources from `index.js`/`config-builder.js` in package.json `aurelia.resources.build`

The second point is a lot of work and once we're able to load selected parts of Materialize I'm afraid this has to be the work of the user or else everything is included in the bundle. That means: I think we can include these resources in *our* package.json but then everyone who uses the bridge will have bundled everything (as long as there is no `exclude` option).

Also users would have to do that twice. Once in `package.json` and another time in `main.js`. Resources have to match everything defined by `bridge.use*()`.

As Materialize is **at the moment* not able to be divided into parts we can safely ignore this **for now** and make it work first. But we should do the following in addition to have a "use-all solution":

* find a way for package.json resources to use everything in the bridge with a one-liner

**Comment by hwaastad** [comment]
@Thanood, 
Hi, care to share your standalone materialize with the new skeleton?
I've been working a bit with the same but it seems navigation destroys my materialize customattributes.

**Comment by Thanood** [comment]
@hwaastad It has evolved and uses the bridge now. But that should be easy to remove. :smile: 
I will upload the test.

**Comment by Thanood** [comment]
@hwaastad https://github.com/Thanood/webpack-materialize

**Comment by hwaastad** [comment]
@Thanood ,
much appreciated. :-)

**Comment by hwaastad** [comment]
@Thanood ,
Hi I know this is not directly related to the birdige, but using webpack and navigation destroys the javascript components. ex collapsible.
I've testet on typescript-skeleton and materialize-css adding import materialize-css in app.ts, adding ccs require in app.html and using a .collapsible on a ref. This works fine.
in typescript-webpack it fails.

Where should I post this issue?

**Comment by Thanood** [comment]
Wow, I have no clue, really..
This could as well be a jQuery on webpack issue if you're saying that **all** JavaScript components are failing.

Do I get it right that it works without webpack? And that it fails if you're adding webpack to that?
Can you test if anything jQuery works?

If that does not work, I think that's a candidate for the `skeleton-navigation` repo.
Maybe you could also try if Bootstrap's JS works in the original typescript-webpack skeleton. When I'm not completely wrong they only use Bootstrap's CSS. That would make it easier for nianii to test because it removes another unknown variable from the equation.

**Comment by Thanood** [comment]
Just added `materialize-css` as a peer-dependency for npm but keeping this open for status reference on webpack integration.

**Comment by hwaastad** [comment]
It might be a jquery issue.
skeleton-webpack complains about "Unhandled rejection TypeError: $(...).collapsible is not a function"

Same configuration.
I'll have check with the skeleton/webpack guys.

Thanks alot.

**Comment by Thanood** [comment]
From version 0.10.0 on the bridge should be compatible with webpack.
Tested with the current skeleton-webpack (beta 2.0.0).

**Comment by AmareshKulkarni** [comment]
@hwaastad - I kept getting those $().. errors randomly. Not sure if you still have those issues, but I was able to get around them by explicit jquery version dependency("jquery": "~2.1.1")  in my package.json

**Comment by Thanood** [comment]
Yeah, stay away from jQuery 3 with Materialize, it's not working out very well.. :wink:
