### ISSUE TITLE
Changing card color

### ISSUE THREAD

**Issue by kst83** [aurelia-ui-toolkits/aurelia-materialize-bridge#223]
Materializecss allows to change card color (http://materializecss.com/cards.html)
How do you do this in aurelia-materialize-bridge?

**Comment by Thanood** [comment]
There is not really a good way at the moment, at least with our built-in card types.

One of the problems is that Materialize's `card` class sets background to be white. So in order to style from the "outer element" (`md-card`) you would have to override Materialize's card with `background-color: transparent`. Surely something we can add to the bridge's cards.

Here is my attempt at the basic Materialize class on their homepage:
https://gist.run/?id=6d80af01a03d9673b22426169bcfc3a8

This indicates to me that our cards still can be improved. :smile:
