### ISSUE TITLE
UglifyJS JS_Parse_Error

### ISSUE THREAD

**Issue by LeoNero** [aurelia-ui-toolkits/aurelia-materialize-bridge#226]
Hi. Since I started using aurelia-materialize-bridge (as stated in #205), I am continually getting the following error:

 ```
 Writing vendor-bundle.js...
{ uid: 10,
  name: 'writeBundles',
  branch: false,
  error: 
   JS_Parse_Error {
     message: 'SyntaxError: Unexpected token: operator (<)',
     filename: 0,
     line: 31736,
     col: 0,
     pos: 980849,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/home/leonardo/my-project/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/home/leonardo/my_project/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n },
  duration: [ 36, 449058741 ],
  time: 1470700707802 }

```

This error never happened before (I'm using the project generated by Aurelia CLI)... what should I do?

**Comment by Thanood** [comment]
Hey..
Since Materialize has a lot of problems with requirejs (the cli uses requirejs), it's maybe better to use a fork which enables using Materialize with requirejs. I'm still evaluating this (going slow atm)..

Can you please check if this issue comment helps in any way?
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/205#issuecomment-236288489

It worked for me up until a certain point (didn't try to make the bridge export everything).
If that works, I will need to add documentation. I'm not sure if it can be solved using Materialize alone (that is without using a clone).

**Comment by Thanood** [comment]
Your error message seems to be exactly what we're getting from aurelia-cli in the comment above.
That's actually a good thing, getting nearer to a solution. :smile:

**Comment by LeoNero** [comment]
Your solution in #205  worked for me! Thanks!
