### ISSUE TITLE
change the doc viewer/gitter tab to not use a fixed height

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#23]
If possible, change the doc viewer/gitter tab to not use a fixed height but fill the screen instead. Maybe use flexbox or absolute positioning.
Not sure how the gitter tab behaves then.

**Comment by adriatic** [comment]
We should certainly do this on all bridges - the current behavior in KendoUI bridge was just a quick hack to verify the correct function of the content.

In general, all of our bridges should behave according to the "mobile first" principle, which (at least in KendoUI bridge comes as a consequence of using Bootstrap layout with rows and columns, since nobody did the research on whether a similar functionality exists in other toolkits (Kendo, Materialize) and we did not discuss what sense does it make to ensure that the Catalog app of each bridge uses only that bridge's target toolkit's controls.

**Comment by Thanood** [comment]
I've tried to do that.
It seems like the gitter container needs a fixed height.

**Comment by Thanood** [comment]
Apart from Gitter chat it's done.

**Comment by adriatic** [comment]
Gitter chat page (implemented as the side-car) is really a placeholder as it this implementation it does not offer anything.

The real version will be aurelia app using gitter API, so we could do a lot of good things here
