### ISSUE TITLE
md-colors not getting bundled

### ISSUE THREAD

**Issue by kottmast** [aurelia-ui-toolkits/aurelia-materialize-bridge#272]
Using aurelia-cli. Installed materialize-css and bridge as described (http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation).

When I load the resulting page, there is an extra request for http://localhost/app/dist/node_modules/aurelia-materialize-bridge/dist/amd/colors/md-colors.js.

I have added an extra build step to copy index.html and bundles into a dist directory, so node_modules is not available at this url and the request gets a 404. I can see in the vendor_bundle.js that most of the other md-xyz scripts are bundled, but md-colors is not. 

In fact, even:
```javascript
define('aurelia-materialize-bridge/colors/colorValueConverters',["exports"], function ...
```
from colorValueConverters.js is included in the vendor bundle, but md-colors.js is not.

au --version: 0.19.0
"aurelia-materialize-bridge": "^0.15.0",
"materialize-css": "^0.97.7",

**Comment by Thanood** [comment]
@kottmast 
That happens when I forget to add things to global exports.. 😃 

Sorry about that and thanks for mentioning, I willl add it in.

If you need it immediately you could edit the file `node_modules/aurelia-materialize_bridge/dist/amd/index.js` and add `'./colors/md-colors'` to [the define here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/dist/amd/index.js#L1) and add `_mdColors` to the function parameters in this line - the two entries must have the same position in their arrays.

Short form:
```javascript
define([ ... , './colors/md-colors', ... ], function(... ,_mdColors, ...);
```

Finally, copy [these lines](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/dist/amd/index.js#L170-L178) and change them to this:

```javascript
  Object.keys(_mdColors).forEach(function (key) {
    if (key === "default") return;
    Object.defineProperty(exports, key, {
      enumerable: true,
      get: function () {
        return _mdColors[key];
      }
    });
  });
```

This is not tested but should work in principle (at least this is how AMD works). 😃
