### ISSUE TITLE
Using webpack the side nav component can not be triggered

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#317]
Not sure if this is a bug or I am just not setting up correctly.

I am using webpack and I can't get the side nav component to work. When I load the page I get the error
Unhandled rejection TypeError: $(...).sideNav is not a function

Example
https://github.com/glennpierce/partyzone_test

Thanks

**Comment by Thanood** [comment]
Would you mind trying this?
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/297#issuecomment-260199214

It worked for me but I'm not sure if it's good enough to put into the docs.
Actually, the only reaction I've got is a "confused" emote. :smiley: 

If you have any hints on how to *really* solve this, I'd greatly appreciate it. I'm not the most experienced webpack user, tbh.

The problem here seems to be that Materialize finishes to initialize itself *after* Aurelia called all `attached()` handlers, so the side-nav component tries to call `$(...).sideNav` before Materialize adds `$.fn.sideNav` to the jQuery object.

So I had the idea to somehow make sure that Materialize finishes first and I noticed that the webpack skeleton does something similar for `aurelia-polyfills`. That's why I've added `materialize-css` to the `bootstrap` bundle because I know that this entry point is bundled first using the `CommonsChunkPlugin`.

**Comment by glennpierce** [comment]
No that didn't work.

Although interesting that also introduces the md-waves bug where the button gets progressively darker with each click. This was after I commented import 'materialize-css'; in main.ts

**Comment by Thanood** [comment]
Thanks for trying.

The dimmed buttons are actually a similar problem.
I tried to "solve" this by putting the following in `main.js` before aurelia starts:

```javascript
  if (window.Waves) {
    window.Waves.displayEffect = function() {};
  }
```

Not pretty, but it seems to work.

Honestly, global modules initializing themselves during "import" should be banned or something..
Not sure what to do, tbh.. At least I can clone your reproduction and use it as another testing ground.

I think this began when we removed the dependency on `materialize-css` from the package (but that may be a coincidence again because global modules...). I wonder if I break something if I put it back in.

**Comment by Thanood** [comment]
This may be something completely different.
Materialize, `window` and the bridge might each have "their own" `jQuery`..
https://github.com/Dogfalo/materialize/issues/3676

So, I've added this to your `webpack.config.js` (right before ""module.exports):

```javascript
config.resolve.alias = {
  '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
  'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
};
```

Changed the bridge source in `node_modules` to use `jQuery` instead of `$` and it worked!

**Comment by Thanood** [comment]
On a side-note, you should probably downgrade `jQuery` to something below v3 - Materialize still has issues with jQuery 3.

**Comment by glennpierce** [comment]
Confirmed working.  Thanks
So glad, I have just spent the last few hours trying to understand webpack / easy-webpack.

I have come to the conclusion someone needs to write an easy-easy-webpack module :)

**Comment by Thanood** [comment]
Great! I'm so glad it works.
A very-easy-webpack module would be great, indeed.. 😉

**Comment by Thanood** [comment]
documented
