### ISSUE TITLE
sidebar is disable when shown.

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#320]
This may be another webpack issue I didn't notice before.

When activating a side bar the bar displays but is greyed out.

Example
https://github.com/glennpierce/partyzone_test

I can't see any errors thrown.

I have tried not to use jquery 3
but

npm list jquery versions shows

├─┬ @easy-webpack/config-global-jquery@1.2.0
│ └── jquery@3.1.1
├── jquery@2.2.4
└─┬ materialize-css@0.97.8
  └── jquery@2.2.4

not sure I can remove it from @easy-webpack/config-global-jquery

**Comment by glennpierce** [comment]
Hmm not sure it is a bug.

I have the sidenav on a page with a nav bar difined as

<md-navbar md-fixed="true">

Taking the md-fixed of the nav bar solves the issue.

Could there be a work around to display the sideNav over the navbar ?

**Comment by glennpierce** [comment]
Ok I moved  side out of the navbar element and add z-index to the style of the sidebar to solve this

**Comment by Thanood** [comment]
Just for reference: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/319 😃 

I'm also not sure if this is a bug or due to Materialize slightly refactoring the side-nav (["minor side nav fixes"](https://github.com/Dogfalo/materialize/releases/tag/v0.97.8)). But I guess it's the second.
TBH, I think the "sidebar outside navbar" approach is even easier to understand/follow.
