### ISSUE TITLE
Follow NPM Semver recommendations

### ISSUE THREAD

**Issue by djensen47** [aurelia-ui-toolkits/aurelia-materialize-bridge#330]
Great project but, unfortunately, I'm missing point releases because this is a 0.x release.

Please follow Npm Inc's recommendations: 

> If a project is going to be shared with others, it should start at 1.0.0, though some projects on npm don't follow this rule.

https://docs.npmjs.com/getting-started/semantic-versioning

Cheers!

**Comment by Thanood** [comment]
Hi @djensen47, thanks for your feedback. 😃 

I'm trying to follow semver rules for pre-release versions because so far I thought this project doesn't satisfy to be a "1.0". One of the downsides of not having a roadmap to a 1.0 release, sorry for that.

Your post made me think, maybe we have reached that point now.. What do you think?
Materialize bridge is certainly at least a beta and I didn't use the `1.0.0-beta.1.0.0` pattern but I've read somewhere that these ranges behave just like the `0.x.x` ones.

But you may be right. Apart from a recent breaking change in Materialize itself the bridge API appears to be stable. Some things are still missing. Occasional missing `disabled` attributes may happen, I'm not really satisfied with `md-colors` because it also contains "non-colors" css needed for some attributes (validation). Webpack install instructions change as often as the webpack-plugin for Aurelia changes but okay, that may be a third-party problem..

What do you think, is this a 1.0?
Maybe I shall at least put up a roadmap.

**Comment by djensen47** [comment]
Well, _I_ think it's a 1.0 😉

**Comment by Kukks** [comment]
I don't know, I would hold from a 1.0 mark till the loaders can load this project with ease. I can see CLI & webpack related issues constantly popping up and they scare a lot of devs from investing into using the library. Other than that, I'm not sure how everything is, havent' had time to work on/with  the bridge in a few months. :(

**Comment by Thanood** [comment]
Any specific CLI issues? I know webpack goes crazy but the CLI should be okay.
TBH I don't know when webpack will *ever* be able to load this project reliably. Maybe when their 2.0 is stable. Let's face it: Materialize is not exactly made for module systems. :smiley:

**Comment by Thanood** [comment]
@Kukks I've added the most common (and most annoying) webpack issue to the 1.0 milestone (#337).
When we get this resolved, I think we should be okay.

Webpack support with Aurelia is unfortunately still a moving target, so you're right. But I also think this is, as opposed to the problem mentioned above, not a bridge issue. It's more of a how-to-configure-multiple-jqueries-with-materialize-and-global-side-effects-issue. 😃
