### ISSUE TITLE
Select element not working with Value Converters

### ISSUE THREAD

**Issue by eikaramba** [aurelia-ui-toolkits/aurelia-materialize-bridge#332]
Given the select example (http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/binding-to-objects), if i  add a value converter to dynamically filter the array, then the select dialog always stays the same as it was intialized with. The `<option>` DOM elements actually changes, but the `<li>` elements do not.

Steps to reproduce:

1. Use Select element like this
```
<md-checkbox md-checked.bind="shouldFilter"></md-checkbox> <-- NEW
<select md-select value.two-way="selectedMeal">
      <option disabled>Select your meal</option>
      <option repeat.for="meal of food | filterPizza:shouldFilter" <-- NEW
       model.bind="meal">${meal.name}</option>
</select>
```

2. Add value converter
```
export class FilterPizzaValueConverter {
  toView(array,toFilterOrNotToFilter) {
    if(array)
    return array.filter(r => {
      return !toFilterOrNotToFilter || r.name==='Pizza';
    });
  }
```

**Comment by Thanood** [comment]
You're transforming the array dynamically. I guess you would need to use [refresh](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/refresh) on that select, too..

It's interesting though, that the select dropdown actually changes when you activate the filter. I wouldn't have expected that. It doesn't change back to the full list when deactivating the filter, though.

Here's a gist illustrating the problem:
https://gist.run/?id=db1c3aeb0495f47c9c0afbd5dbbd8b58
Is the gist correct?

There is currently no elegant way to propagate changes in options to the Materialize select control. That's why I wonder why the dropdown list is actually refreshed when activating the filter.

**Comment by Thanood** [comment]
This app.js works:

```javascript
import {observable} from 'aurelia-framework';

export class BasicUse {
  @observable() shouldFilter = false;
  
  food = [
    { id: 0, name: 'Pizza' },
    { id: 1, name: 'Cake' },
    { id: 2, name: 'Steak' },
    { id: 3, name: 'Pasta' },
    { id: 4, name: 'Fries' }
  ];
  selectedMeal = this.food[1];

  setSelectedMeal() {
    this.selectedMeal = this.food[2];
  }
  
  shouldFilterChanged() {
    this.select.refresh();
  }
}
```

I didn't want to save the gist because I'm not sure if you've already seen it. 😃 
Of course you would also have to save a `ref` to md-select in the view.
`<select md-select md-select.ref="select" value.two-way="selectedMeal">`

**Comment by eikaramba** [comment]
Thank you so much!
FYI:
_Interestingly your gist already worked better than my local version of it, because somehow initializing `selectedMeal `will improve it in a way, that at least the first triggering of the checkbox will refresh the options. Now i added the multiple option(because actually that is my requirement) and guess what, back to quare one. Nothing works._

However your tip with the `refresh()` and `observable `works flawlessly! 👍 See this gist for a final solution with multiple: https://gist.run/?id=4b0124b6ffc5af3e101a58909ff3e6be

I think that would made a good addition to the docs. i cannot be the only one dynamically repeating and filtering options :)
