### ISSUE TITLE
Textarea does not autoresize

### ISSUE THREAD

**Issue by swiftanthony** [aurelia-ui-toolkits/aurelia-materialize-bridge#338]
https://gist.run/?id=9a3c06adf7e9587207d63b1148bad5ef

This is the gist from the documentation. Textarea does not autoresize.

**Comment by Thanood** [comment]
Thanks. :smiley: 
It's because of this: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/103#issuecomment-188442117

In the sample it should work because I added a `hiddendiv` which Materialize textareas expect for auto-resizing. I tried it in the gist jsut now (in `index.html`) but it doesn't change anything. I should put this as a comment into a documentation file, though.

**Comment by swiftanthony** [comment]
Thanks

**Comment by HIRANO-Satoshi** [comment]
I experienced that the hiddendiv did not work for our "fullbleed" app which body has class="fullbleed" and the fullbleed is defined like this.

```
/* always full height  */
body.fullbleed {    
    margin: 0;
    height: 100vh;
    overflow: hidden;  /* inhibit body scrolling */
}
```

```
  <body aurelia-app="main" class="fullbleed"></body>
```

Here is another workaround using *autosize*.

```
$ npm install autosize --save
```

```
import * as autosize from 'autosize';

    attached() {
        // make textarea autoresize by the autosize library
        var textarea:any = document.querySelector('.materialize-textarea');
        autosize(textarea);
    }
```

```
<template>
  <style>
   .materialize-textarea {
     min-height: 200px !important;
   }
  </style>
  <md-input md-label="Label" md-value.bind="var1" md-text-area="true"> </md-input>
```

**Comment by Thanood** [comment]
Thank you @HIRANO-Satoshi 😃
