### ISSUE TITLE
Surface corresponding onOpen/onClose callbacks for Collapsible

### ISSUE THREAD

**Issue by drub0y** [aurelia-ui-toolkits/aurelia-materialize-bridge#348]
The `collapsible` plug-in offers `onOpen`/`onClose` callbacks. It would be most useful if the Aurelia control surfaced those and/or fired events through the event aggregator.

**Comment by drub0y** [comment]
Just looked into doing this work in a PR and realized the materialize.js implementation being used is 0.97.7 and the `onOpen/onClosed` callbacks were implemented in 0.97.**8**. I would not feel comfortable upgrading the dependency as part of just my work and would rather see it upgraded as a standalone PR. 

I will postpone my work until there is guidance provided on moving to this newer version.

**Comment by Thanood** [comment]
Thanks for pointing out `onOpen`/`onClose` - I didn't see that addition.

May I ask where did you get the impression that the materialize.js implementation being used is 0.97.7? I may be unclear somewhere and I'd like to be more explicit in that case.
This is interesting as I've been using 0.97.8 for quite a while.

Technically, #307 is completed. I left it open for some reason I don't remember.
Don't let that stop you from creating a PR. 😃

**Comment by drub0y** [comment]
@Thanood Well I was just going by the fact when I cloned the project and did `npm install` and `jspm_install` I ended up with version `0.97.*7*` in the root `jspm_packages`. However, I see now that the `samples/jspm_packages` is `0.97.*8*`. The cause of the root of the project being `.7` is because that's the version that the root `config.js` specifies. In fact there are two entries for the `materialize` lib in the `map` section. 

Also note that both the project and the `samples` include `materialize` as a dependency in `package.json`, but both are calling for `0.9*7.5*` which is obviously quite behind, but it really doesn't matter since JSPM is being used here. Additionally note that the version listed for `peerDependencies` in `package.json` is `0.9*7.6*`. 

So, clearly there's a little bit of confusion within the project itself. Is it worth entering a separate issue and corresponding PR to address these versioning issues? That's how I'd choose to do it, I just wanted to get your thoughts.

**Comment by Thanood** [comment]
Thank you for clarifying.

The Materialize versions relevant for a `jspm` installation are all at `^0.97.5` (see [here](github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/package.json) and [here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/package.json#L23)). I thought with the semver `^` modifier the most current in `0.x` range is used. Is that not correct? I'm actally unsure because I have done some semver related mistakes in the past. 😃 

Btw. [this entry in `config.js`](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/config.js#L37-L40) lists the direct `jspm` dependencies of `github:Dogfalo/materialize@0.97.7`. Just for completeness if that's the second entry you meant.

[This entry](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L111) (which is at `^0.97.6`) is actually used in `npm` based installations, so webpack or aurelia-cli.
It's only a `peerDependency` to allow for using forks. In fact this bridge does not depend directly on Materialize at all. It just expects that it's there.

To be honest, I don't always update the root to the latest Materialize version since it seemed not so relevant for me. The sample, on the other hand, needs the most recent version because that is the version actually used at runtime.

> Is it worth entering a separate issue and corresponding PR to address these versioning issues?

If you'd like to do it (I don't think that you actually need to) you can just place it in the same PR. 😃
