### ISSUE TITLE
Line ending situation on Windows is confusing

### ISSUE THREAD

**Issue by drub0y** [aurelia-ui-toolkits/aurelia-materialize-bridge#351]
The average developer who has set `core.autocrlf=true` currently ends up with `crlf` line endings in their working directory, but as soon as they opened any file in VSCode, even just to read it, it would change all the line endings to `lf` due to the `.editorconfig` `end_of_line = lf` setting (such as VSCode). This makes it look like the developer changed the entire file even though they didn't touch anything.

While this ultimately has no direct impact on the repo, it creates confusion for the developer and, IMHO, a less than friendly workflow for new contributors who might be diving in.

There's two ways to fix this:

 1. Add a `.gitattributes` file to the repo which will force all line endings to `lf` for `text` files in the working directory _even on Windows_ because otherwise there is a conflict with editors that respect the `.editorconfig` `end_of_line=lf` setting (such as VSCode). The negative effect of this change would be that, for users who might use simple editors that expect `crlf` on Windows will not be happy. For example, if you open any text file in `notepad.exe` you're gonna end up with a one line view of the file. Considering there's already a bit of a dependency on `.editorconfig` this might not be a concern. If it is a concern then see 2.

 --- OR ---

 2. Remove the `end_of_line = lf` from `.editorconfig` and just rely on `git` to normalize everything to `lf`.

**Comment by drub0y** [comment]
I have a branch ready to PR that does option 1, but I'm not convinced it's the best thing for the repo. The more I think about it, option 2 is probably the better solution as it's what most people are familiar with and provides the least friction for Windows developers. I'll get that option read for a PR too. 

Please decide which you want and let me know here and then I'll submit the corresponding PR.

**Comment by adriatic** [comment]
> Add a .gitattributes file to the repo which will force all line endings to lf for text files in the working directory even on Windows because otherwise there is a conflict with editors that respect the .editorconfig end_of_line=lf setting (such as VSCode). 

This is certainly the better of the two options, so I am suggesting to @JeroenVinke that we follow this practice in KendoUI bridge and Monterey project.

Thank you @drub0y for raising this to the level where it caught my attention :-)

**Comment by drub0y** [comment]
No worries, I'll PR that option to you right now for you guys to review.

**Comment by adriatic** [comment]
Only after I read your comment [above](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/351#issuecomment-271033981), I realized that I may have misread your proposal - so I am leaving this as is, with the preference to resolve it tomorrow when my Europe based partners resurface again.

**Comment by drub0y** [comment]
No worries. If the decision switches to option 2 then I'll just cancel the current PR and submit one for that. Cheers!

**Comment by Thanood** [comment]
I'm not sure since option 2 relies on the user having their config set correctly, right?
According to the [git docs](https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration) it's best for Linux users to set `core.autocrlf` to `input` if they are collaborating with Windows users.

> This setup should leave you with CRLF endings in Windows checkouts, but LF endings on Mac and Linux systems and in the repository.

Regarding the drawbacks of option 1: If one really uses a text editor that only understands CRLF nowadays, I think they can't work with GitHub repos at all. Maybe that's even a weak argument but I've never seen any editor (except notepad) which doesn't support any line endings in the last 10 years or so. 😃 

I like the idea a lot in general since git is the "last authority" before files are commited to GitHub.

> The more I think about it, option 2 is probably the better solution

I'm on the same boat, the more I think about it..
Please let's discuss this a little further. What do others think?

@adriatic Why is option 1 certainly the better option?

**Comment by Thanood** [comment]
Btw. I feel like this is rather "new" (like a few years or so):

> The average developer who has set core.autocrlf=true

And came with the introduction of the recent git GUIs. GitKraken, GitHub client and I think SourceTree recommend this (some even set this silently). On the other hand it was always the suggested solution for Windows developers. May just be that I didn't use it personally because it caused some confusion in the past.

**Comment by drub0y** [comment]
> Btw. I feel like this is rather "new" (like a few years or so)

Yes, it's true it used to be that you had to set this yourself a couple years ago, but, as you pointed out, it's the default with the major Windows Git installers nowadays (even the "raw" GitHub for Windows installer sets it as the default), so I would think this is a safe bet. Also, if you just make sure you add some notes in `contributing.md` and keep an eye out for it in PRs I'm pretty sure you have your bases covered and it does guarantee the "best" experience for both platforms' developers.

So, I still vote for option 2, but I'll wait for a final word here before canceling the current PR (which is currently for option 1) and submitting the other.

**Comment by Thanood** [comment]
In this case I'd like to hear @adriatic's opinion. 😃

**Comment by adriatic** [comment]
The second alternative presented **[above](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/351#issue-199311512)** seems more generic as it does not depend on the editors various contributors use. 

I think that we are pretty well attached to GitHub (speaking for myself of course), so what happens when we want to include BitBucket as the additional playground, should be also handled at the Git repository level.

**Comment by Thanood** [comment]
As long as we use git, we're safe. Bitbucket supports git.
And I'm pretty sure Mercurial hasa a similar setting.

**Comment by Thanood** [comment]
Let's do option 2.. 😃

**Comment by drub0y** [comment]
There's the infinitely simpler PR for option 2. :D
