### ISSUE TITLE
Advanced autocomplete?

### ISSUE THREAD

**Issue by djensen47** [aurelia-ui-toolkits/aurelia-materialize-bridge#356]
The way that Materialize does autocomplete is problematic. I would post this issue there but there are so many issues for Materialize that they seem to get ignored.

Let's say you have a collection of fruit that you want to autocomplete: apple, pear, orange. Now, let's say that these fruits correspond to a record in a database. Now, let's try to internationalize this. Finally, let's allow _only_ values that are found in the array.

Ideally, construct would be an array of objects:

```javascript
[{
    value: t('apple'),
    id: 'tr456yui876ytr456yui8',
    image: 'http://images/apple.jpg'
}]
```

Any thoughts on this or is it out of scope because Materialize has no built-in way to handle this?

**Comment by djensen47** [comment]
I just found this and it looks great: https://github.com/icefox0801/materialize-autocomplete

**Comment by Thanood** [comment]
While I certainly agree that Materialize autocomplete can be improved a lot I'm hesitant about advancing the built-in functionality too much. Here is why:

- compatibility: The editable chips feature has also been asked for. Believe it or not, two weeks later Materialize had one. 😃 While I had nothing to do with that, unfortunately, imaging if I had implemented this in a completely different way. Or even integrated a third-party control ([this one](http://henrychavez.github.io/materialize-tags/examples/) or [this one](http://www.jqueryscript.net/demo/Material-Design-Tags-Input-Plugin-with-jQuery-Materialize-Tags/), see #87). Now that would have been a breaking change because users comfortable with our implementation would either have to adapt to Materialize's new feature or continue to use the bridge's one which causes a lot of confusion.
- Materialize updates: staying close to the original library is important IMO. At the moment I can just adapt to changes in Materialize and be happy with it, maybe contribute to some fixes and PRs and hope these will be fixed/integrated. If one of the third-party components is out of date or not compatible with the most recent Materialize version (f.i. modals) that will cause some problems.
- third-party updates: Materialize itself uses f.i. Waves and pickadate. It does not depend on these projects and change the appearance but rather integrates them tightly. The way Materialize is built, you cannot update either of them or even use a fork. Now if I integrate icefox0801's solution I'd either introduce a dependency which some people may not want or integrate it in the same way Materialize does and I'd have to maintain that. 😉 
- APIs: this may be personal taste nowadays but I'm really not a fan of coupling the API (service fetching autocomplete data from a database) to the view too much. From this point of view you'd have a way to translate the API response anyway for the view to understand it (because what if it changes? you'd have to adapt the app). So you could translate the `[apple, pear, orange]` array to values autocomplete understands. I've added a `refresh()` function to autocomplete to allow for this ([see here](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/autocomplete-basic-use), click "set other values"). I do believe that Materialize will add a `refresh()` themselves one day because it's been asked a lot of times and I think it's essential.

Having said that I do believe we could wrap icefox0801's autocomplete into a custom attribute. Ideally this would be another project as a contribution to this (bridge)  project. Or if it's simple enough we have a section for contributions [here](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/recipes-autofocus). Maybe we can add it there.

If you see any other way to integrate https://github.com/icefox0801/materialize-autocomplete without introducing a direct dependency, please let me know. I really like that autocomplete implementation. 😃

**Comment by Thanood** [comment]
Okay, tldr: I've just seen acburst has self-assigned your issue on Materialize repo and so I guess we'll see that functionality implemented. 😏

**Comment by djensen47** [comment]
Thanks for the thoughtful response.

Until the MaterializeCSS improvements are available, I'm going to try to wrap @icefox9891's library.

**Comment by djensen47** [comment]
Looks like the Materialize team implemented chips, which wasn't really the only thing that I was suggesting.

Instead of trying to figure out how to wrap icefox9891's library, I decide to create my own "native aurelia" attribute to handle autocomplete.

**Comment by Thanood** [comment]
Wow, I wonder how did they get that impression.. I would have thought they'd do a generic autocomplete and then combine it with chips.

> I decide to create my own "native aurelia" attribute to handle autocomplete.

That's a great idea! 👍 
Let me know how it's going, please. Maybe we can add a sample to the "contributions" section later.
Or I could just "GitHub-watch" it. 😃

**Comment by djensen47** [comment]
I've posted it as a gist. I'll turn it into a full on plugin at some later date.

https://gist.github.com/djensen47/189d785171367280c7f79a3fe30b6f23

It's still a work in progress but it's basically working.

**Comment by Thanood** [comment]
Looks good. 😃 

Maybe you'd like to use `BindingEngine` instead of `ObserverLocator`, as according to [this SO post](http://stackoverflow.com/questions/28419242/property-change-subscription-with-aurelia/28437456#28437456) `Observerlocator` seems to be an internal api.

**Comment by djensen47** [comment]
Thanks for the tip, I'll make the change.

**Comment by djensen47** [comment]
I've updated the Gist with the suggested change as well as some fixes. It still could use some code cleanup, the workflow became a little wonky.

**Comment by Thanood** [comment]
How do you test it? I'd suggest creating a gist.run from your gist which imports the bridge bundles.
I've tried that yesterday but I couldn't get it to work and didn't have enough time. I could prepare such a "playground" from your gist, if you like.

**Comment by djensen47** [comment]
I'm testing it in my local dev environment and I haven't split it into it's own module yet. 😞

**Comment by Thanood** [comment]
I'll try to come up with a gist tomorrow. It's easier to comprehend for me.
Could you give a little guidance on how to use it? Last time I tried, I failed to "connect" the autocomplete to my test data.

**Comment by djensen47** [comment]
Sorry for the late response. I've subscribed to ALL updates on this project and I fell behind reading them.

Let me add a sample usage to the gist tonight.

**Comment by avrahamcool** [comment]
@djensen47 if you can publish your plugin it will be very helpful.
we are in a need for multiple selection with autocomplete

**Comment by MaximBalaganskiy** [comment]
M v1 introduced a new method to update the data which is now used by the bridge when values change
