### ISSUE TITLE
running bundled materialize seems to require typescript

### ISSUE THREAD

**Issue by halllo** [aurelia-ui-toolkits/aurelia-materialize-bridge#365]
I am bundling materialize and aurelia-materialize-brige into the vendor bundle. Running the bundle does not work because it somehow seems to require typescript:

> "GET /config.js"
> "GET /jspm_packages/system.js"
> "GET /dist/vendor.js"
> "GET /jspm_packages/npm/typescript@2.1.5.js"
> **"GET /jspm_packages/npm/typescript@2.1.5.js" Error (404): "Not found"**

It does not request typescript when I run it unbundled. Could be a loader issue in combination with materialize.

I am using npm:aurelia-materialize-bridge@0.22.0 and github:Dogfalo/materialize@0.97.8 and my repository is at https://github.com/halllo/AureliaTutorial/tree/master/materialize-starter.

What can I do to have materialize bundled and loaded correctly?

**Comment by Thanood** [comment]
@halllo Your `config.js` has a typescript transpiler specified here: https://github.com/halllo/AureliaTutorial/blob/master/materialize-starter/config.js#L4

Is this also the case with the bundled app?

**Comment by halllo** [comment]
Yes, it is there in the bundled app. But I does not seem to matter with all the other bundles. Only the bundle that has materialize in it crashes. It looks like materialize needs to be transpiled in the browser, which is not what I want.
Is there a way to get a already transpiled version of materialize anywhere?

**Comment by Thanood** [comment]
It is already transpiled (from ESnext btw., not TypeScript) to SystemJS format.

The JSPM config uses the `dist/system` directory of this repo ([see here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L31-L34)). That means this directory is being used: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/tree/master/dist/system

The catalog app is also a bundled JSPM app. It uses a Babel transpiler for the samples, though.
Maybe this helps: https://github.com/aurelia-ui-toolkits/demo-materialize
Bundle config: https://github.com/aurelia-ui-toolkits/demo-materialize/blob/master/build/bundles.js

This is strange since there is no TypeScript involved either in the bridge or Materialize itself. Also both use transpiled sources.

**Comment by halllo** [comment]
I still don't get why only the bundled version does not work.

Thank you. Please do, I am going crazy here 😃

**Comment by Thanood** [comment]
I've got some completely different errors so I don't know if this helps.

First, I removed JSPM forks of jquery and isarray:

```
jspm resolve --only npm:jquery@2.2.4
jspm resolve --only npm:isarray@1.0.0
```

Then, I've changed the bundle config to produce a separate Materialize bundle. When I did not do that, Materialize wouldn't find `Picker` somehow.

After that, I've changed how the bridge is bundled, leaving out `.d.ts` files.

Here is the complete `bundles.js` which works for me:

```javascript
module.exports = {
  "bundles": {
    "dist/app-build": {
      "includes": [
        "[**/*.js]",
        "**/*.html!text",
        "**/*.css!text"
      ],
      "options": {
        "inject": true,
        "minify": true,
        "depCache": true,
        "rev": false
      }
    },
    "dist/vendor": {
      "includes": [
        "aurelia-framework",
        "aurelia-bootstrapper",
        "aurelia-fetch-client",
        "aurelia-router",
        "aurelia-templating-binding",
        "aurelia-polyfills",
        "aurelia-templating-resources",
        "aurelia-templating-router",
        "aurelia-loader-default",
        "aurelia-history-browser",
        "aurelia-logging-console",
        "aurelia-pal-browser",
        "text",
        "fetch",
        "jquery",
        "[aurelia-materialize-bridge]",
        "[aurelia-materialize-bridge/**/*.js]",
        "aurelia-materialize-bridge/**/*.css!text",
        "aurelia-materialize-bridge/**/*.html!text"
      ],
      "options": {
        "inject": true,
        "minify": true,
        "depCache": false,
        "rev": false
      }
    },
    "dist/materialize": {
      "includes": [
        "materialize"
      ],
      "options": {
        "inject": true,
        "minify": true,
        "rev": true
      }
    }
  }
};

```

**Comment by Thanood** [comment]
Maybe I should leave the `.d.ts` files in `dist` and remove them from the loader directories. Not sure if that will break anything though.

**Comment by halllo** [comment]
Thanks, now the bundle works. I added the starter template from materialize.

But in the bundled version md-waves (button in welcome.html) does not work. Also the sideNav (nav-bar.ts) does not work.
In the unbundled version everything works great. I think there still could be something wrong with the bundle dependencies.
Do you have an idea?

**Comment by Thanood** [comment]
Can you specify what "does not work" means in both cases? 😃 
I've cloned the current version of your repo and tried it. Everything seems to work bundled and unbundled.

One thing, maybe unrelated.. You initialized the sidenav manually [here](https://github.com/halllo/AureliaTutorial/blob/master/materialize-starter/src/nav-bar.ts#L11-L13). Of course, that's okay if you like to do so. Using [the didenav component](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/sidenav-basic-use) prevents a TS transpilation error on line 3 of that file since you don't need to use jQuery directly.

Also, the sidenav has some problems when it's contained inside the `<nav>` tags of the top nav bar. When you close it, its overlay stays on top. Try to move the sidenav `<ul>` outside of `<nav>`.

I didn't have any problems with `Waves`, though.
Are there any errors?

**Comment by halllo** [comment]
Sure, I will check out the sidenav component. But I think I have a more general problem.
When I run the bundled version (`gulp export && http-server -o -c-1 export`) there is no wave effect when I click the button. And the sideNav does not appear when the browser window is small and I click the hamburger. There are no errors in the browser console.

**Comment by Thanood** [comment]
Interesting. I just did the same (`gulp export && http-server -o -c-1 export`) and I've seen waves and the sideNav. Which browser did you test with?

**Comment by halllo** [comment]
I tested Edge 38 and Chrome 55 on Windows. And I just uploaded my export directory to https://labs.neokc.de/materialize/. If I run it from there I see the sideNav-TypeError in the browser console. But I also don't see waves. Do you see waves?

**Comment by Thanood** [comment]
Weird..
It fails at [this line](https://github.com/halllo/AureliaTutorial/blob/master/materialize-starter/src/nav-bar.ts#L12): `(<any>$('.button-collapse')).sideNav();`

And I guess I didn't encounter the error because I've commented that out and used `md-sidenav`.
I suppose Materialize is not loaded completely at that point (which always confuses me like hell).

I wonder if loading Materialize via a standard `<script>` tag is the most reliable sulution to that problem. I know it's not pretty and I'm not sure if it works at all.
I've come up with this (brute-force) approach for webpack which has a similar problem:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/337#issuecomment-267434505

Can you try that?

**Comment by halllo** [comment]
Like this https://github.com/halllo/AureliaTutorial/blob/master/materialize-starter/src/main.ts#L7?
Does not seem to work...

**Comment by Thanood** [comment]
Yes, like this..

Sorry, I didn't have the time yet to look at that. I'd try logging `$`, `jQuery` and `jQuery.fn.sideNav` as I suppose it's not there, yet. Which, again, is quite strange since this `attached()` business should happen well after any `DOMContentLoaded` event and after Materialize is initialized completely.

It could also be that two jQuery versions are active at the same time and you get "the other" in `attached()`.

**Comment by halllo** [comment]
Perfect, no the sidebar and the waves work :)
Thanks a lot.

**Comment by halllo** [comment]
I want to `import {MdInputUpdateService} from 'aurelia-materialize-bridge';` but somehow the `aurelia-materialize-bridge.d.ts` is not recognized:

> Cannot find module 'aurelia-materialize-bridge'

**Comment by Thanood** [comment]
When using JSPM, the typings are not automatically discovered.

Please try:
```
typings install aurelia-materialize-bridge=github:aurelia-ui-toolkits/aurelia-materialize-bridge/dist /aurelia-materialize-bridge.d.ts --save
```

**Comment by halllo** [comment]
Perfect. Thank you!
