### ISSUE TITLE
DatePicker in modal doesn't work

### ISSUE THREAD

**Issue by rokadias** [aurelia-ui-toolkits/aurelia-materialize-bridge#380]
I was having issues with the datepicker in a modal dialog since overflow is hidden, and truncates the bottom of the secondary dialog for the date picker.

So I found an issue described in materialize, and mentions use of container.
https://github.com/Dogfalo/materialize/issues/1032

I've followed the instructions in materialize, but it doesn't seem to fix the problem. I think I've narrowed it down to code in the bridge that attaches it back to the parent of the element. I've tried changing this to attach to the container instead, but it doesn't seem to work.
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/datepicker/datepicker.js#L113

The blame/annotation on the line of code above doesn't help me figure out why it was done. So I can't seem to figure out a pull request here.

**Comment by Kukks** [comment]
Yeah, that was my doing. It was done so that tab-indexing doesn't break with the materialize date-picker. As an example, without that method, when you tab into the datepicker element, the datepicker does not open and acts like it skipped it. It would however pop up once you're at the last element at the end of the page and tab since the modal is generated there. 

I guess a flag boolean whether to toggle that functionality would be ok for you but I wish there was a way of getting the best of both worlds..

**Comment by Thanood** [comment]
I thought `this.picker.$root` is the *picker*  itself, not the input..
@Kukks would it still work if you move `this.picker.$node` closer to the source?

Just an idea..
If you tab into the input, it retrieves focus and should open the picker, right?

If that doesn't help, we could provide a flag as you mentioned.

**Comment by Kukks** [comment]
@Thanood Last I checked, datepicker only opened on focus of its own element not the input field :/  It could eb different now though, I haven't been able to get my hands on a project using this bridge again so far.

**Comment by Thanood** [comment]
@Kukks You're right, I tried it and it doesn't work.

Now for My concern regarding the current solution: We introduce an automatic option to solve tab targetting, changing the default behaviour. We would now introduce another option to bring the default behaviour back..

Furthermore, tab targetting is easily solvable by using the `container` option:

```html
      <div ref="dpWrapper">
        <input md-datepicker="container.bind: dpWrapper; value.two-way: selectedDate;" type="date" placeholder="pick a date" />
      </div>
```

Which does the same as `movePickerCloserToSrc()`.
Unfortunately, when using `movePickerCloserToSrc()`, the opposite is not so easily obtainable because when you set `container` to anything else it basically has no effect.

So my proposal in this case is:
- either remove `movePickerCloserToSrc()` and document the workaround mentioned above
- or make `movePickerCloserToSrc()` the option with the default being *not* to use it

Any objections/ideas? 😃
