### ISSUE TITLE
Installation docs are confusing

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#381]
Hi

The section of the docs that says

Important: This doesn't work out of the box with Materialize versions lesser than v0.97.8 anymore since they removed leanModal.js.
Instead, add the following files to your project root directory: rbuild.js and materialize-css.js

These files contain leanModal.

However, The two files that don't contain leanModal are the two links above that sentence.

I ended up downloading the wrong ones. I believe this is why the is a comment from Markus Dessler
saying the same.
(Hope this makes sense)

Thanks

**Comment by Thanood** [comment]
Yes, you're definitely not the only one. And I agree.
I was thinking of some variations to make it better but I didn't settle on anything specific.

Then I thought, now with `au import` available I could first create an importer so that all of this isn't necessary (you'd just do `au import aurelia-materialize-bridge` and be ready).

But that's just delaying improvement of the docs. So now I will do *that* first. 😃

**Comment by Thanood** [comment]
@glennpierce Please check the [updates docs](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html) if you find some time. I hope this is less confusong now. 😃

**Comment by glennpierce** [comment]
That looks good to me.

**Comment by MaximBalaganskiy** [comment]
See updated docs
