### ISSUE TITLE
md-char-counter in md-input not working in version 0.24.0

### ISSUE THREAD

**Issue by avrahamcool** [aurelia-ui-toolkits/aurelia-materialize-bridge#389]
[the demo](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input-character-counter) do **NOT** work. [if it does for you, clean cache and refresh the page]
but the [gist](https://gist.run/?id=008631e09037fe0edf804368b75326e6) is working.
I've notice that the gist is running against `aurelia-materialize-bundles/0.20.2`, and I think that the counter do NOT work in `0.24,0` (the version I'm running in my project).

I've tried to change the gist to run against 0.24.0 by changing
`<script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.20.2/config2.js"></script>
` to
`<script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.24.0/config2.js"</script>
`
but other errors occurred (the config is nt proper).
so I cant provide a gist that shows the counter is not working

**Comment by Thanood** [comment]
I can see the counter not working, thanks. 👍 
I just wonder why. And if the configuration of 0.24.0 causes errors, I should have a look at that, too.

**Comment by Thanood** [comment]
Apparently, I've still set the `length` attribute while Materialize 0.98 expects the `data-length` attribute to be set. I've changed that.

**Comment by Thanood** [comment]
The 0.25.0 bundles work again: https://gist.run/?id=482a13eb873f6e44de9af9d79dd16c2b
But I had to add this:

```html
<require from="materialize/dist/css/materialize.css"></require>
```

Because there is no hard dependency on materialize css anymore, it's not pulled automatically (as it was the case with 0.20.x bundles). I'd like to find a workaround because these gists aren't really compatible with the bridge app.

(also copying this comment to #390)
