### ISSUE TITLE
show/hide md-datepicker using icon is buggy

### ISSUE THREAD

**Issue by avrahamcool** [aurelia-ui-toolkits/aurelia-materialize-bridge#396]
I'm initializing a `md-datepicker` with an icon the same as the [demo](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/datepicker-advanced-options),
 and it has a strange behaviour when showing/hiding using `show.bind` and `if.bind`.

`show.bind` - a single icon is created, but hiding the input don't hide  the icon, hiding the containing div actually works fine.
`if.bind` - hiding the input don't hides the icon, and every time the input shows up - a new icon is created.
when hiding the div, the icon also hide, but every time a new icon is added.

I created a [gist](https://gist.run/?id=1e150e2103c58affbb7f9d6c261fb09f) to show all of this.

**Comment by Thanood** [comment]
My guess is this happens because the icon is not removed in `unbind()`..
Big oversight.. Thanks for finding that out. 👍

**Comment by Thanood** [comment]
Quick fix: https://gist.run/?id=9a3de27aea854abd0ff091ca46d11790

Doesn't solve show.bind, though.
That's because the icon is a sibling of the input element. It would need to be hidden, too.

**Comment by avrahamcool** [comment]
what if the code of the datepicker generation will enclose the picker and the icon in a single aurelia `template` tag, and apply the `show`/`if` on that tag..
then - from the browser point view, you dont see this virtual `template` tag, but from aurelia point of view  - setting `show` to false will hide this tag and all of his component.
is it even possible?

**Comment by Thanood** [comment]
TBH, I'm not a fan of it because you're changing the element's HTML. IMO, that's okay for a custom element but not a custom attribute. It should leave the attached element as it is (because who knows what the user is going to do with it).

I know, the icon is something similar and I'm kind of "breaking my own rule" here. But it's adding html to it's parent, not altering the element itself.. Anyway, I'd rather not make it worse and introduce even more HTML tinkering. 😃 

Makes me think... How to improve the icon?

But your solution has an advantage. If you (as a user) put the picker inside of a `<template>` and show/hide that it should affect the icon, too. We could document that.

**Comment by avrahamcool** [comment]
good point.
