### ISSUE TITLE
optimize dependencies

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#402]
Continuation of:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/391#issuecomment-292998812

**Comment by mreiche** [comment]
I'm currently writing documentation about bundling the bridge using aurelia bundler for JSPM/SystemJS including materialize-css.

https://github.com/mreiche/materialize-bridge-docs/blob/master/app_developers_notes/bundling_with_jspm.md

But before publishing that, I want to make sure that I completly understand the behaviour of JSPM dependencies and NPM dependencies within the bundling process. Because my aurelia-materialize-bundle doesn't work out-of-the box, there are several issues about that. *Note:* Im bundling for a LAMP application, not a NodeJS based.

### Unable to bundle materialize-css with the bridge

I have 2 bundles:
* The main *aurelia-bundle* contains the complete aurelia framework plus additional libraries.
* The *material-bundle* contains the materialize, the bridge and jquery.

But when trying to bundle the materialize-bridge with *materialize-css*
```
"materialize-css",
"[aurelia-materialize-bridge]",
"[aurelia-materialize-bridge/**/*.js]",
"aurelia-materialize-bridge/**/*.css!text",
"aurelia-materialize-bridge/**/*.html!text"
```

Im getting the following error:

> Uncaught (in promise) Error: (SystemJS) Cannot set property 'Picker' of undefined
	TypeError: Cannot set property 'Picker' of undefined

```javascript
"function" == typeof define && define.amd ? define("picker", ["jquery"], a) : "object" == typeof exports ? module.exports = a(require("jquery")) : this.Picker = a(b)
```
To get this work, I need to bundle *materialize-css* in my *aurelia-bundle*

```
'aurelia-...',
'materialize-css'
'jquery'
```

Do you have an idea what could be the reason that *materialize-css* needs to be bundled before the bridge?

**Comment by Thanood** [comment]
I'm not sure right now.. There are a lot of problems bundling Materialize with any bundler. Just look at all their issues regarding webpack, browserify etc. in Materialize issue tracker.

**disclaimer:** I'm far from being an aurelia-bundler expert. 😃 

I *think* it depends on "where" jQuery is bundled (or rather when it is initialized). I think that error is related to having two or more jQuery instances active in the application. But that's not a sure thing, tbh.

If you look at how the catalog app is bundled ([here](https://github.com/aurelia-ui-toolkits/demo-materialize/blob/master/build/bundles.js)) you'll see that materialize is bundled in its own, separate bundle while jquery and the bridge are bundled in a `pluginsBundle` which is merged with the app bundle.

My guess is that this works because jQuery is loaded immediately with the app bundle. And there is only a single installation of jquery. For example it's not `Dogfalo/materialize` **and** `npm:materialize-css` in the bundle.

With webpack it's pretty obvious. If you don't assign the expression `jquery` to a single source (via `ProvidePlugin`) then you get the same error about `Picker` (among other errors).

**Comment by Thanood** [comment]
I just remembered an issue with dependencies.

Materialize has no restriction on jquery versions while it's not compatible with jQuery 3.
The bridge has `jquery@^2.2.4` - thus, when you install it with jspm, the more restrictive jquery version is used which is jquery 2.

**Comment by adriatic** [comment]
This same issue, (which is the consequence of the interaction between jspm and jQuery that I never understood other than seeing that "something does not work right") is still present in KendoUI bridge code. We fixed it by completely isolating KendoUI's "own" jQuery instance, which uses the reference different from any known jQuery aliases, can then coexist with KendoUI bridge user's code using their own jQuery.

It would be nice to finally solve this puzzle so the end user app does not have to have to jQuery instances loaded.

**Comment by mreiche** [comment]
@Thanood wrote:
> Materialize has no restriction on jquery versions while it's not compatible with jQuery 3.

You mean it **has** restrictions? jQuery 2.x is fine for me. It's just the behaviour of JSPM to always install the newest version, which is not really a flaw.

@adriatic 
> It would be nice to finally solve this puzzle so the end user app does not have to have to jQuery instances loaded.

We solved this "bundling puzzle" by using multiple bundles as described above. Where *materialize-css* and *jquery* are both bundled into the *aurelia-main-bundle*. We are currently working hard on a final production release. When this is running, im willing to complete the bundling documentation and exchange my experience.

**Comment by Thanood** [comment]
Hmm, no I meant it doesn't have restrictions. But you are right that it **has** restrictions.

**Comment by Thanood** [comment]
Just to be completely sure. This is what we're talking about, right?
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L36-L43

**Comment by MaximBalaganskiy** [comment]
The demo app is using JSPM to produce a bundle for gists. There are currently no issues with this.
