### ISSUE TITLE
md-tabs indicator does not work by API

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia-ui-toolkits/aurelia-materialize-bridge#409]
Hi,

The examples in the doc for md-tabs works.

     http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/tabs-api

But the the gist.run linked from the above page does not work. "SELECT TAB 2" button does not move the indicator.

    https://gist.run/?id=6a238e618806289a3800dd4560cf1959

This issue seems like #392 but 'tabs_2' is correct.

**Comment by Thanood** [comment]
Hi @HIRANO-Satoshi.

It's because of `md-waves` on tabs. The workaround mentioned in "basic use" is not applied to the gist but it is globally applied in the bridge app.

If you add this css it should work:

```css
[md-tabs] .waves-effect {
  position: static;
}
```

Or, remove waves from tabs.
Unfortunately, there are some more problems with waves on tabs since (I think) the last Materialize version. For example in the "basic use" sample, the tabs show no waves effect at all. And in the code preview tabs, the effect position is wrong.

**Comment by HIRANO-Satoshi** [comment]
Thanks for reply.

I tried to add the [md-tabs] code to the gistrun, the indicator worked.

I agree with you about the waves. I gave up waves in our app.

**Comment by MaximBalaganskiy** [comment]
All works in the demo now

**Comment by HIRANO-Satoshi** [comment]
Thanks!
