### ISSUE TITLE
md-collection-item: click.delegate does not propagate event to md-collection-selector

### ISSUE THREAD

**Issue by bebor** [aurelia-ui-toolkits/aurelia-materialize-bridge#411]
when having `click.delegate` on `md-collection-item`, the event gets not propagated to the `selector`, therefore in effect its is not clickable anymore

see gist: https://gist.run/?id=2eaee16d6ed34655b92d8e26747a9977

there is a click.delegate in the collection-item, that does only console.log. when clicking on the selector, the event is consumed by the `md-collection-item click.delegate`

**Comment by Thanood** [comment]
Quick fix:

Return `true` from `testClick()`..

```js
  testClick(event){
    this.logger.log(event);
    return true;
  }
```

Any "real" solution is appreciated of course. 😃 
I don't think using `trigger` in the selector is a good one because there may be a lot of collection items and thus a lot of event listeners (`delegate` compensates for that).

Maybe returning `false` from that handler on the selector (forcing events to not bubble) would work.

**Comment by MaximBalaganskiy** [comment]
Please check on the upgraded demo. Reopen if persists.
