### ISSUE TITLE
Add input field suffixes

### ISSUE THREAD

**Issue by jasoncarreira** [aurelia-ui-toolkits/aurelia-materialize-bridge#422]
Like https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/150 there should be the ability to add suffixes to input fields. 

Like it shows here: https://material.io/guidelines/components/text-fields.html#text-fields-input-types it would be good to be able to use arbitrary text for prefixes and suffixes

**Comment by Thanood** [comment]
Thanks for your feedback. 👍 

There are already some entries in materialize's issue tracker requesting input suffixes.
[For example this one](https://github.com/Dogfalo/materialize/issues/2489). Althoug it is closed, it has a corresponding PR and links to another issue where the team is tracking suffixes.

Also there is this "meta" issue where all Material components are tracked now: https://github.com/Dogfalo/materialize/issues/4553

Tbh, I'd rather not implement that directly, as this feature will likely be added to Materialize itself and we introduce a lot of (compatibility)  problems if we go our own way with certain features. The latest example for that (auto-height nav-bar), albeit simple, forced us to introduce the same functionality twice because there are now users of the "old" auto-height and of course Materialize users expect the new Materialize auto-height to work as they expect it. 😃

**Comment by jasoncarreira** [comment]
Ah, understood. I thought this was already in MaterializeCSS which is why I thought it should be added here. Waiting for it to be added to MaterializeCSS is probably a good idea.
