### ISSUE TITLE
md-select: dropdown is clipped 

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia-ui-toolkits/aurelia-materialize-bridge#433]
Hi, 

Dropdown of *<select*> is clipped at browser's bottom end like this, because *<ul*> has *"top: 0px;"*. It should be *"top: -158px;"* as shown in the last image.

![image](https://user-images.githubusercontent.com/1736529/27112270-f62ebfa0-50f0-11e7-8fd9-b2ef54cccaac.png)

You can see *<ul*> has *top: 0px;*.

![image](https://user-images.githubusercontent.com/1736529/27112831-67a8a134-50f4-11e7-98c2-d89d3cc69048.png)

It is okay at Materialize demo. 

![image](https://user-images.githubusercontent.com/1736529/27112320-5905da3c-50f1-11e7-9efa-91e9002d05ef.png)

*<ul*> has *top: -158px;*.

![image](https://user-images.githubusercontent.com/1736529/27112847-7d64ac0c-50f4-11e7-8488-ae3604964ec8.png)

**Comment by HIRANO-Satoshi** [comment]
Here is a very quick fix.

```
<template>
  <style>
   ul.select-dropdown {
     top: -200px !important;
   }   
  </style>

    <select md-select>
      <option model.bind="null" disabled>Select an item</option>
      <option repeat.for="item of items" model.bind="item">
      </option>
    </select>
    ....
```

**Comment by Thanood** [comment]
Materialize sets the `top` property dynamically and the default is `top: 0px;`.
If the menu appeared offscreen, it would adjust the position so the dropdown is visible. This is where `top: -158px;` is set.

Apparently, this doesn't happen. 😄 
I think this could be due to some css in the bridge catalog. I'll have a look at it.

**Comment by HIRANO-Satoshi** [comment]
Thanks, Daniel. That also happens in our app.

**Comment by Thanood** [comment]
So, after a lot of trying and looking at the dropdown code, I finally had the idea to check vanilla Materialize in a CodePen. 😃 

Unfortunately, it happens there, too: https://codepen.io/anon/pen/MobWBm
(with all 0.98.x versions)

So I'm wondering if they're using a different version on their homepage.
I'm going to search the issue tracker.

**Comment by Thanood** [comment]
Okay, got it (took so long because I had to fix a broken node 8 installation).
The function to open the dropdown is triggered twice and the second time the inner height of the `<ul>` is somehow calculated as `0` which means (of course)  that it would fit on screen.

Now, I'll check why it's called twice. 😕

**Comment by Thanood** [comment]
Fixed it but not comitted yet because I need to check for side-effects.
This is the bad guy: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/select/select.js#L130

The dropdown is initialized twice, thus its trigger handler is initialized twice.
Why its height is calculated as `0px` escapes me but that's not the error in question here.

**Comment by HIRANO-Satoshi** [comment]
Great! Thank you very much!

select seems complicated.

It's not urgent for me, since I have the quick fix. I will wait for the next release.
