### ISSUE TITLE
New version includes all files

### ISSUE THREAD

**Issue by istrau3** [aurelia-ui-toolkits/aurelia-materialize-bridge#435]
PLATFORM.moduleName() is processed **at build time**. 

The plugin has source code like this:
```
 useCheckbox(): ConfigBuilder {
    this.globalResources.push(PLATFORM.moduleName('./checkbox/checkbox'));
    return this;
  }
```
but this does not prevent './checkbox/checkbox' from being included in the final bundle since the call to `PLATFORM.moduleName()` is processed at build time.

I am not sure what the point of configuration is if all the resources are included anyway...

**Comment by Thanood** [comment]
Right, what's the point..? Unfortunately I never documented my explanation for that decision and now I forgot the details. That's a mistake I'll try not to do ever again. 😃 

As far as I remember, there are three alternative approaches to this problem, two of them leading to the state where everything is bundled. The third had the implication that we would have to change the infrastructure of this project completely to both support run-time configuration (SystemJS/requirejs) and build-time configuration (webpack).

If you have any idea how to solve this problem, it would be greatly appreciated.

Naive example: what if we would configure an additional file which only webpack users would import? That file could f.i. use `ModuleDependenciesPlugin` to define dependencies and as default provide everything.

I'm not a webpack expert so I'm not sure if this would work at all. The file should be ignored if you *don't* want to import everything. This would at least provide a choice.

I have another problem with that kind of configuration:
Materialize itself is not modular. You get the complete thing regardless of what you do. So is it worth the effort?

**Comment by Thanood** [comment]
More info on that topic: https://github.com/aurelia/webpack-plugin/issues/107#issuecomment-293878340

**Comment by istrau2** [comment]
@Thanood Well, you could always use this approach: https://github.com/aurelia/framework/blob/master/src/framework-configuration.js

I mean, the aurelia framework itself works with all the supported loaders. It allows you to optionally include resources in the bundle.

For example, look at this line:
https://github.com/aurelia/framework/blob/master/src/framework-configuration.js#L315

You could probably just hook into one of the aurelia frameworks methods actually. I realize the devil is in the details (as it always is) but just thought I would throw out the suggestion =).

I am kind of busy over the next week but if you want I could try and create a pull request at some point (although it would probably be more difficult for me since I am not too familiar with the aurelia-materialize-bridge source).

**Comment by Thanood** [comment]
> since I am not too familiar with the aurelia-materialize-bridge source

That shouldn't be a problem, we can always work on that part. 😏 

One difference that I see with the framework's approach is that they load different modules (packages) depending on the configuration. These are modules the user would have to add to the webpack bundle.
Materialize bridge is one single module.

IMO that's a significant difference since you can easily "not include" a module in a bundle.
But I'm curious what your PR will contain. Maybe I misunderstood something. 😃

**Comment by istrau2** [comment]
@ Thanood I believe that when you make the call to PLATFORM.moduleName('foo') that creates a webpack module. In any case, I can try and submit something over the next 2 weeks to a month I guess.

**Comment by Thanood** [comment]
If you want to, please do so. I'm always happy for some webpack insights. :smiley:

> I believe that when you make the call to PLATFORM.moduleName('foo') that creates a webpack module

True, but it doesn't work dynamically.
The first version had a `.map(m => PLATFORM.moduleName(m))` of the config's result. But that doesn't work since webpack (of course) doesn't evaluate that expression at build time.
(but, strange enough, it worked for custom elements, just not attributes)

I think the only way to do this is via `ModuleDependenciesPlugin` or creating one module for each element and have users actively import the module they want in their code.

The idea with the second approach is that webpack will scan that import at build time and only include dependencies which are used.
