### ISSUE TITLE
Support for DropDown stopPropagation

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-materialize-bridge#451]
As questioned here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/450
materialize-css  has an option for the dropdown element named *stopPropagation* (http://materializecss.com/dropdown.html) which is currently no supported by the bridge.

**Comment by Thanood** [comment]
I could swear I checked **all** dropdown options in v0.98.0 -.-
Thanks for mentioning, I will get this in. 👍

**Comment by mreiche** [comment]
The current version is 0.99 ;)

**Comment by Thanood** [comment]
I know but I thought they'd put that into the change log..
Okay, that was naive. 😂

**Comment by FariJan** [comment]
Are there any news? I want to use this option too.

**Comment by Thanood** [comment]
Sorry, lack of time at the moment.. I'll try to get it in tomorrow.

**Comment by Thanood** [comment]
@mreiche Are you sure this does what you want?
Thanks to @vulvulune's PR it's in master but I had a look and it doesn't prevent the dropdown from closing.

Here is an example using vanilla Materialize: https://codepen.io/anon/pen/wqvqey

I guess it *could* work since the dropdown is hidden on `document` click which should not reach up to `document` level but apparently it doesn't.

Please tell me if I overlooked something.

**Comment by Thanood** [comment]
It's in 0.30.0.

**Comment by mreiche** [comment]
> The option was removed from M v1

This option is now called `closeOnClick `.

**Comment by MaximBalaganskiy** [comment]
That one is in the options and exposed as an attribute

**Comment by dipakchandranp** [comment]
Hi I am initializing materia dropdown using following code:
`var instances = M.Dropdown.init(elems); `

How to pass `stopPropagation` property in this?
