### ISSUE TITLE
Bug: Selects after a browser-default one is not displayed

### ISSUE THREAD

**Issue by vulvulune** [aurelia-ui-toolkits/aurelia-materialize-bridge#456]
If there are multiple select in a page, all selects (without `browser-default`) after one with the class  `browser-default` are not displayed.

It's not a Materializecss bug because without the bridge, it's okay.

A gist with the bug: (This gist is with 0.27 version, but the bug is still here in the 0.29 version)
https://gist.run/?id=38262dd6d1281fa14496066128519a11
The select value 3 is missing.

A code pen directly with Materializecss:
https://codepen.io/anon/pen/owVePr
All is okay except the label for the second select.

The callstack (with version 0.29):
`select.js:254 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
at MdSelect.observeVisibleDropdownContent (select.js:254)
at MdSelect.createMaterialSelect (select.js:216)
at select.js:116
at TaskQueue.flushTaskQueue (aurelia-task-queue.js:117)
at aurelia-task-queue.js:77
at handleFlushTimer (aurelia-task-queue.js:30)`

I will try to fix this issue myself and publish a PR soon.

**Comment by Thanood** [comment]
I really think this is happening in the `browser-default` select since this is (rather should not be) not even touched by Materialize. But of course the bridge does its thing..

Frankly, it doesn't make sense to use `md-select` with `browser-default` since the `browser-default` select is nothing but a native select.

So I guess the best fix for that would be for `md-select` to ignore it and do nothing at all. Or throw a warning. What do you think?

**Comment by vulvulune** [comment]
You are right, it's useless to put the both in the same time...

But it should be nice to add a test in the bridge to check if there is the browser-default class, because this css class can be conditional, and we can't have a custom attribute conditonal with aurelia (or I don't know how do this). For sure, the class must be set before the attach.

**Comment by Thanood** [comment]
Good point! 👍

**Comment by vulvulune** [comment]
I will provide a PR soon.
