### ISSUE TITLE
Write "about this application"

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#47]
* [x] [1. Introduction](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-application:-1.-Introduction-(r3))
* [x] [2. Navigation guide](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-application:-2.-Navigation-guide)
* [x] [3. Components catalog](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-Application:-3.-Components-catalog)
* [x] [4. Internal structure](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-Application:-4.-internal-structure)
* [x] [5. Installation](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-application:-5.-Installation)
* [x] [6. Project status](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-application:-6.-Project-status)
* [x] [7. Color switcher](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-application:-7.-Color-switcher)

**Comment by Thanood** [comment]
@adriatic: Having written the [Introduction](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/About-this-application:-1.-Introduction-(r2)) it somehow "felt wrong" to basically just replace "KendoUI" with "Materialize".

The article reads like a brief overview of the history of this bridge. Which is all good and interesting but this history happened with the KendoUI bridge.

Could you please leave a comment and tell me if that is the intention?

**Comment by adriatic** [comment]
> Could you please leave a comment and tell me if that is the intention?

It is not the intention - the current text should be considered just a placeholder. The general rule (driven by the desire to present a consistent Look and Feel to our bridge customers) is that all actual information should be bridge target specific

**Comment by Thanood** [comment]
Thanks for clarification. I don't know where that impression came from. Seems logical to not copy everything.

**Comment by Thanood** [comment]
Regarding 3. component catalog:
I think showing the probably most interesting component (grid in KendoUI) is a very good thing. But I'm not sure what that component might by in Materialize.

So for now I'm going to show the project status, which will become a component overview later. From there, I'll describe the side-nav navigation implemented yesterday.

Any objections or ideas for the "most interesting component"? :smile:

**Comment by adriatic** [comment]
Based on the experience of several people who got lost trying to start from the best start point, KendoUI bridge changed the initial landing page (from Grid) to be the About page (see below)

![image](https://cloud.githubusercontent.com/assets/2712405/12886515/e1450bfa-ce3b-11e5-9aff-31a7874cc306.png)

**Comment by adriatic** [comment]
> Also how did you do that effect on the edges of the screenshots? 

The effect is called `torn edges` and I use a tool called **[Snagit](https://www.techsmith.com/snagit.html)** to make all screenshoots.

**Comment by Thanood** [comment]
How could I not connect those? I even created an issue for the about page.. :smile: 
Also, of course, thanks for mentioning ```torn edges```.

**Comment by adriatic** [comment]
You are doing a "bang-up" job, Daniel - I am very happy that you are a member of our team !!

**Comment by Thanood** [comment]
Thanks alot! I'm feeling honored. :smile: 
I'm also happy to be on the team with such smart people.

I hope I get this documentation ready soon, I have been dodging it long enough. ;-)

**Comment by adriatic** [comment]
Writing documentation in such nice "environment", using markdown, hosting these files in the catalog app, being able to make references to source code in the Github repository - could be really fun (speaking from the experience, as I did most of KendoUI bridge docs). Nothing will test your own understanding of a subject than writing to explain it to others :-)

**Comment by Thanood** [comment]
Indeed.. I found it very interesting writing the app dev tutorial, since I did every step of it myself, so I could see that it actually works that way. :smile:

**Comment by Thanood** [comment]
I'll close this as it is finished considering the current status. The docs will need a review anyway (best from someone other than me).

**Comment by adriatic** [comment]
I will gladly review the docs - let me know when it's ready, please

**Comment by Thanood** [comment]
It's all ready but the bridge developer notes. Links to skeleton-plugin-materialize are broken, of course, as that repo doesn't exist yet.

In my opinion it's better to read them from the catalog app itself and that's only in part because I have used atom to write the last few articles (I found some nice Markdown plugins). ;-)
But I'm quite confident that I've synced the articles with our wiki on GitHub.

**Comment by adriatic** [comment]
> Links to skeleton-plugin-materialize are broken ...

This just made me realize how I did not even plan to have the "target colored" skeleton bridges (like skeleton-materialize bridge). Here is what I was planning before you joined the team 

1. `KendoUI bridge` gets finished
2. We extract from that finished bridge **everything** that we now call "target independent" code and stuff it into it into an empty repo called `skeleton bridge`.
3. When we get the "man power" to start some other bridge, we start with with a copy of that `skeleton` bridge and implement the few UI Boostrap element that exists in the `skeleton bridge`, so that this new bridge can show its initial catalog using the "target UI toolkit aureliaized controls.

Since you became a part of us before we had `skeleton bridge` available (which is still not finished, by the way, as it lacks the "catalog related infrastructure") you became a victim of running an incompletely defined project. 

Note that we will not know what is a complete definition of the `skeleton bridge` until we build all bridges and extract pieces of each new one into `skeleton-bridge`

Now, we can switch the terminology and sat that a `skeleton bridge` is the complete equivalent of the Visual Studio template:

![image](https://cloud.githubusercontent.com/assets/2712405/12901523/371957e0-ce8a-11e5-973b-17c6943e41c3.png)

and that our `bridges` are Aurelia applications built with such templates / `skeleton bridges`

How does this change your perception of this while situation?

**Comment by Thanood** [comment]
I'm about to go to bed so I'll answer in short now.. :smile: 

> How does this change your perception of this while situation?

Not at all, tbh. And I also don't see the connection to skeleton-plugin-materialize links being broken. That will basically become the materialize-bridge-developers-tutorial. I just didn't do it yet.

It's good to compare it to VS templates (or yeoman generators) as I thought the same of skeleton-bridge and the "prototype" (for the lack of words) that you've provided to me.

Here is my imagination of "bridge X" coming to be:
* someone clones skeleton-bridge
* implements the skeleton controls needed to run the catalog app with the target toolkit
* releases the catalog app as an alpha version
* continues to develop the missing components

**Comment by adriatic** [comment]
Ok, we **are** on the same page and the confusion is caused by you using the name `skeleton-plugin-materialize` - which I translated in my head as "skeleton bridge, where the Boostrap UI components are **replaced** by Materialize UI components. Now I think that `skeleton-plugin-materialize` refers to the repository that contains the Materialize equivalent of [skeleton-plugin-kendo](https://github.com/aurelia-ui-toolkits/skeleton-plugin-kendo) - the **tutorial for Materialize developers**.

This shows that we do not have a well defined, easy to use vocabulary (references) to various items we handle daily.

**Comment by Thanood** [comment]
Sorry for the confusion. Again. ;-)

Yes, I meant ```skeleton-plugin-materialize``` => ```materialize-bridge-developers-tutorial``` and I called it "skeleton..." because it's mentioned in the docs that way. I probably should have renamed it **there** in the first place. :smile:
